[[ -f ~/.bashrc ]] && . ~/.bashrc

if [ -z "$DISPLAY" -a $XDG_VTNR -eq 1 ]; then
    startx
    xmodmap -e "keycode 112 = Home"
    xmodmap -e "keycode 117 = End"
    xmodmap -e "keycode 110 = Prior"
    xmodmap -e "keycode 115 = Next"
fi
